# Generated by Django 4.1.9 on 2023-06-25 04:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("cms", "0003_gallerypage_detailsgallerypage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detailsgallerypage",
            options={
                "verbose_name": "Details Gallery Page",
                "verbose_name_plural": "Details Gallery Pages",
            },
        ),
        migrations.AlterModelOptions(
            name="gallerypage",
            options={
                "verbose_name": "Gallery Page",
                "verbose_name_plural": "Gallery Pages",
            },
        ),
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page", "verbose_name_plural": "Home Pages"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="blocks",
            field=wagtail.fields.StreamField(
                [
                    (
                        "category",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        label="Título", max_length=100
                                    ),
                                ),
                                (
                                    "category_page",
                                    wagtail.blocks.PageChooserBlock(label="Categoría"),
                                ),
                                (
                                    "subcategories",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "subcategory",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                label="Título",
                                                                max_length=100,
                                                            ),
                                                        ),
                                                        (
                                                            "author",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "arquitectos",
                                                                        "Henriquez Arquitectos",
                                                                    ),
                                                                    (
                                                                        "gabriel",
                                                                        "Gabriel Henriquez",
                                                                    ),
                                                                    (
                                                                        "jorge",
                                                                        "Jorge Henriquez",
                                                                    ),
                                                                ],
                                                                label="Autor",
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ],
                                        block_counts={
                                            "anchors": {"max_num": 4, "min_num": 1}
                                        },
                                        label="sub-categoras",
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Header menu",
            ),
        ),
        migrations.CreateModel(
            name="CTAButtonDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Label for the button",
                        max_length=255,
                        verbose_name="Label",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="Link for the button",
                        max_length=255,
                        verbose_name="Link",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Page to link to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Page",
                    ),
                ),
            ],
        ),
    ]
