# Generated by Django 4.1.9 on 2023-06-25 04:51

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0004_alter_detailsgallerypage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="blocks",
            field=wagtail.fields.StreamField(
                [
                    (
                        "category",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        label="Título", max_length=100
                                    ),
                                ),
                                (
                                    "category_page",
                                    wagtail.blocks.PageChooserBlock(label="Categoría"),
                                ),
                                (
                                    "subcategories",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "subcategory",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                label="Título",
                                                                max_length=100,
                                                            ),
                                                        ),
                                                        (
                                                            "author",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "arquitectos",
                                                                        "Henriquez Arquitectos",
                                                                    ),
                                                                    (
                                                                        "gabriel",
                                                                        "Gabriel Henriquez",
                                                                    ),
                                                                    (
                                                                        "jorge",
                                                                        "Jorge Henriquez",
                                                                    ),
                                                                ],
                                                                label="Autor",
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ],
                                        block_counts={
                                            "subcategory": {"max_num": 4, "min_num": 1}
                                        },
                                        label="sub-categoras",
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Header menu",
            ),
        ),
    ]
